apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - templates/k8sdisallowlatesttag.yaml
  - templates/k8srequiredlimits.yaml
  - templates/k8spsprootuser.yaml
  - templates/k8spsphostnetwork.yaml

  - constraints/deny-latest.yaml
  - constraints/require-limits.yaml
  - constraints/deny-root.yaml
  - constraints/deny-hostnetwork.yaml
