apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPRunAsUser
metadata:
  name: deny-root-user
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]

  parameters:
    rule: MustRunAsNonRoot
