apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequireOwnerLabel
metadata:
  name: require-owner-label
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]