apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: demo
  name: develop-pods
subjects:
  - kind: User
    name: alice
roleRef:
  kind: Role
  name: pod-developer


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sre-pods
subjects:
  - kind: User
    name: bob
roleRef:
  kind: ClusterRole
  name: pod-sre

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: demo
  name: viewer-pods
subjects:
  - kind: User
    name: carol
roleRef:
  kind: Role
  name: pod-viewer
