apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-password
  namespace: demo
spec:
  refreshInterval: 30s

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: db-secret

  data:
    - secretKey: password

      remoteRef:
        key: prod/db-password