apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: demo
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1

      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret
            key: access-key

          secretAccessKeySecretRef:
            name: aws-secret  
            key: secret-key