# Namespace: Tạo namespace demo cho API workload
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    # Enable Sigstore policy enforcement
    # ⚠️ CHỈ BẬT SAU KHI ĐÃ KÝ IMAGE
    # policy.sigstore.dev/include: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "0"